//
//  HighscoresWireframe.swift
//  Snake
//
//  Created by Zvonimir Medak on 21.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt

final class HighscoresWireframe: BaseWireframe<HighscoresViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard.highscores

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: HighscoresViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = HighscoresInteractor(input: .init(highscoreService: HighscoreService()))
        let presenter = HighscoresPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension HighscoresWireframe: HighscoresWireframeInterface {

    func navigateToHome() {
        navigationController?.popToRootViewController(animated: true)
    }
}
