//
//  HighscoresInteractor.swift
//  Snake
//
//  Created by Zvonimir Medak on 21.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import CombineExt

final class HighscoresInteractor {

    // MARK: - Private properties -

    private let input: Highscores.Input

    // MARK: - Init -

    init(input: Highscores.Input) {
        self.input = input
    }
}

// MARK: - Extensions -

extension HighscoresInteractor: HighscoresInteractorInterface {

    func save(userModel: UserModel) -> AnyPublisher<Void, Error> {
        input.highscoreService.save(userModel: userModel)
    }

    func getHighscores() -> AnyPublisher<[UserModel], Error> {
        input.highscoreService.getHighscores()
    }
}
