//
//  SettingsInterfaces.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt

protocol SettingsWireframeInterface: WireframeInterface {
    func navigateToGameRules(configurators: [ComponentConfigurable])
}

protocol SettingsViewInterface: ViewInterface {
}

protocol SettingsPresenterInterface: PresenterInterface {
    func configure(with output: Settings.ViewOutput) -> Settings.ViewInput
}

protocol SettingsInteractorInterface: InteractorInterface {
    var gameSpeed: GameSpeed { get }
    var arenaSize: ArenaSize { get }
    func update(gameSpeed: GameSpeed)
    func update(arenaSize: ArenaSize)
}

enum Settings {

    struct ViewOutput {
        let rulesAction: Signal<Void>
    }

    struct ViewInput {
        let viewConfiguration: ViewConfiguration
    }

    struct ViewConfiguration {
        let gameSpeedPickerItem: PickerViewItem
        let arenaSizePickerItem: PickerViewItem
    }

    struct Input {
        let userStorage: DefaultsStorageInterface
    }
}
