//
//  SettingsInteractor.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import CombineExt

final class SettingsInteractor {

    // MARK: - Private properties -

    private let input: Settings.Input

    // MARK: - Init -

    init(input: Settings.Input) {
        self.input = input
    }
}

// MARK: - Extensions -

extension SettingsInteractor: SettingsInteractorInterface {

    var gameSpeed: GameSpeed {
        input.userStorage.gameSpeed
    }

    var arenaSize: ArenaSize {
        input.userStorage.arenaSize
    }

    func update(gameSpeed: GameSpeed) {
        input.userStorage.gameSpeed = gameSpeed
    }

    func update(arenaSize: ArenaSize) {
        input.userStorage.arenaSize = arenaSize
    }
}
