//
//  SettingsViewController.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt
import CombineCocoa

final class SettingsViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet private weak var rulesButton: UIButton!
    @IBOutlet weak var gameSpeedPickerView: PickerView!
    @IBOutlet weak var arenaSizePickerView: PickerView!


    // MARK: - Public properties -

    var presenter: SettingsPresenterInterface!

    // MARK: - Private properties -

    private var cancellables: Set<AnyCancellable> = []

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
}

// MARK: - Extensions -

extension SettingsViewController: SettingsViewInterface {
}

// MARK: - View setup

private extension SettingsViewController {

    func setupView() {
        let output = Settings.ViewOutput(
            rulesAction: rulesButton.tapPublisher.asSignal()
        )

        let input = presenter.configure(with: output)
        handle(viewConfiguration: input.viewConfiguration)
    }
}

// MARK: - UI setup

private extension SettingsViewController {

    func handle(viewConfiguration: Settings.ViewConfiguration) {
        gameSpeedPickerView.configure(with: viewConfiguration.gameSpeedPickerItem)
        arenaSizePickerView.configure(with: viewConfiguration.arenaSizePickerItem)
    }
}
