//
//  UserFormWireframe.swift
//  Snake
//
//  Created by Zvonimir Medak on 22.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt

final class UserFormWireframe: BaseWireframe<UserFormViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard.userForm

    private let userActionRelay: PassthroughRelay<UserForm.Action>

    // MARK: - Module setup -

    init(score: Float, userActionRelay: PassthroughRelay<UserForm.Action>) {
        let moduleViewController = storyboard.instantiateViewController(ofType: UserFormViewController.self)
        self.userActionRelay = userActionRelay

        super.init(viewController: moduleViewController)

        let interactor = UserFormInteractor(input: .init(score: score, highscoreService: HighscoreService()))
        let presenter = UserFormPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension UserFormWireframe: UserFormWireframeInterface {
    
    func navigateToResult(userAction: UserForm.Action) {
        userActionRelay.accept(userAction)
    }
}
