//
//  UserFormInteractor.swift
//  Snake
//
//  Created by Zvonimir Medak on 22.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import CombineExt

final class UserFormInteractor {

    // MARK: - Private properties -

    private let input: UserForm.Input

    // MARK: - Init -

    init(input: UserForm.Input) {
        self.input = input
    }
}

// MARK: - Extensions -

extension UserFormInteractor: UserFormInteractorInterface {

    var score: Float {
        input.score
    }

    func save(userModel: UserModel) -> AnyPublisher<Void, Error> {
        input.highscoreService.save(userModel: userModel)
    }
}
