//
//  HomeViewController.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineCocoa

final class HomeViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet private weak var playButton: SnakeButton!
    @IBOutlet private weak var highscoresButton: SnakeButton!
    @IBOutlet private weak var settingsButton: UIBarButtonItem!


    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Private properties -

    private var cancellables: Set<AnyCancellable> = []

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}

// MARK: - View setup

private extension HomeViewController {

    func setupView() {
        setupUI()

        let output = Home.ViewOutput(
            playAction: playButton.tapPublisher.asSignal(),
            highscoresAction: highscoresButton.tapPublisher.asSignal(),
            settingsAction: settingsButton.tapPublisher.asSignal()
        )

        _ = presenter.configure(with: output)
    }
}

// MARK: - UI setup

private extension HomeViewController {

    func setupUI() {
        playButton.configure(for: .primary)
        highscoresButton.configure(for: .secondary)
    }
}
