//
//  HomeInterfaces.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func navigateToSettings()
    func navigateToGame()
    func navigateToSettingsInformation(input: PageSheet.Input)
    func navigateToHighscores()
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    @discardableResult
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
    var shouldShowSettingsInformation: Bool { get }
    func update(shouldShowSettingsInformation: Bool)
}

enum Home {

    struct ViewOutput {
        let playAction: Signal<Void>
        let highscoresAction: Signal<Void>
        let settingsAction: Signal<Void>
    }

    struct ViewInput {
    }

    struct Input {
        let userStorage: DefaultsStorageInterface
    }
}
