//
//  HomeWireframe.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe<UIViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard.home

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: HomeViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = HomeInteractor(input: .init(userStorage: UserStorage.instance))
        let presenter = HomePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {

    func navigateToGame() {
        navigationController?.pushWireframe(GameWireframe())
    }

    func navigateToSettings() {
        navigationController?.pushWireframe(SettingsWireframe())
    }

    func navigateToHighscores() {
        navigationController?.pushWireframe(HighscoresWireframe())
    }

    func navigateToSettingsInformation(input: PageSheet.Input) {
        let wireframe = PageSheetWireframe(input: input)
        navigationController?.present(wireframe.viewController, animated: true)
    }
}
