//
//  PageSheetInteractor.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import CombineExt

final class PageSheetInteractor {

    // MARK: - Private properties -

    private let input: PageSheet.Input

    // MARK: - Init -

    init(input: PageSheet.Input) {
        self.input = input
    }
}

// MARK: - Extensions -

extension PageSheetInteractor: PageSheetInteractorInterface {

    var configurators: [ComponentConfigurable] {
        input.configurators
    }
}
