//
//  PageSheetPresenter.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import CombineExt

final class PageSheetPresenter {

    // MARK: - Private properties -

    private unowned let view: PageSheetViewInterface
    private let interactor: PageSheetInteractorInterface
    private let wireframe: PageSheetWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: PageSheetViewInterface,
        interactor: PageSheetInteractorInterface,
        wireframe: PageSheetWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PageSheetPresenter: PageSheetPresenterInterface {

    func configure(with output: PageSheet.ViewOutput) -> PageSheet.ViewInput {
        return PageSheet.ViewInput(configurators: interactor.configurators)
    }
}
