//
//  PageSheetInterfaces.swift
//  Snake
//
//  Created by Zvonimir Medak on 20.06.2022..
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineExt

protocol PageSheetWireframeInterface: WireframeInterface {
}

protocol PageSheetViewInterface: ViewInterface {
}

protocol PageSheetPresenterInterface: PresenterInterface {
    func configure(with output: PageSheet.ViewOutput) -> PageSheet.ViewInput
}

protocol PageSheetInteractorInterface: InteractorInterface {
    var configurators: [ComponentConfigurable] { get }
}

enum PageSheet {

    struct ViewOutput {
    }

    struct ViewInput {
        let configurators: [ComponentConfigurable]
    }

    struct Input {
        let configurators: [ComponentConfigurable]
    }
}
